#!/usr/bin/env python

import numpy
import h5py
import pyscf.lib.parameters as param
from pyscf.scf import hf
from pyscf.pbc import gto, scf, dft, df
from pyscf.pbc import lib as libpbc
from pyscf.pbc.tools import pbc
from pyscf import lib

name = 'k-lif'
cell = libpbc.chkfile.load_cell(name+'.chk')
cell.ecp = None
mo_coeff_kpts = lib.chkfile.load(name+'.chk', 'scf/mo_coeff')
mo_occ_kpts = lib.chkfile.load(name+'.chk', 'scf/mo_occ')
kpts = lib.chkfile.load(name+'.chk', 'scf/kpts')
nkpts = len(mo_occ_kpts)
dm_kpts = [hf.make_rdm1(mo_coeff_kpts[k], mo_occ_kpts[k]) for k in range(nkpts)]
dm_kpts = lib.asarray(dm_kpts)

supercell = [1,1,1]
grid = [50,50,50]
ngrid = numpy.asarray(grid)
nX, nY, nZ = tuple((numpy.asarray(grid)-1)*numpy.asarray(supercell) + 1)
nx, ny, nz = numpy.asarray(grid)

super_cell = pbc.super_cell(cell, supercell)
lattice = super_cell.lattice_vectors() * param.BOHR
symbols = [atom[0] for atom in super_cell._atom]
cart = numpy.asarray([(numpy.asarray(atom[1])* param.BOHR).tolist() for atom in super_cell._atom])
num_atoms = super_cell.natm		

qv = lib.cartesian_prod([numpy.arange(i) for i in ngrid])
a_frac = numpy.einsum('i,ij->ij', 1./(ngrid - 1), cell.lattice_vectors())
coords = numpy.dot(qv, a_frac)
#coords = numpy.asarray(coords, order='C')

ao = dft.numint.eval_ao_kpts(cell, coords, kpts=kpts, deriv=0)
rho = 0.0
for k in range(nkpts):
    rho += dft.numint.eval_rho2(cell, ao[k], mo_coeff_kpts[k], mo_occ_kpts[k], xctype='LDA')
rho *= 1./nkpts
valores = numpy.empty([nX, nY, nZ])
valores_tmp = numpy.empty([nX, nY, nZ])
rho = rho.reshape([nx,ny,nz])
for x in range(supercell[0]):
    for y in range(supercell[1]):
        for z in range(supercell[2]):
            valores_tmp[:nx,:ny,((nz-1)*z):((nz-1)*z + nz)] = rho
        valores_tmp[:,((ny-1)*y):((ny-1)*y + ny),:] = valores_tmp[:,:ny,:]
    valores[((nx-1)*x):((nx-1)*x + nx),:,:] = valores_tmp[:nx,:,:]

with open(name + '_den.xsf', 'w') as f:
    f.write('Generated by pyscf\n\n')		
    f.write('CRYSTAL\n')
    f.write('PRIMVEC\n')	
    for row in range(3):
    	f.write('%10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
    f.write('PRIMVEC\n')
    for row in range(3):
    	f.write('%10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
    f.write('PRIMCOORD\n')
    f.write('%3d %3d\n' % (num_atoms, 1))
    for atom in range(len(symbols)):
    	f.write('%s  %7.7f  %7.7f  %7.7f\n' % (symbols[atom], cart[atom][0], cart[atom][1], cart[atom][2]))				
    f.write('\n\n')			
    f.write('BEGIN_BLOCK_DATAGRID_3D\n3D_field\nBEGIN_DATAGRID_3D_UNKNOWN\n')	
    f.write('   %5d	 %5d  %5d\n' % (nX, nY, nZ))		
    f.write('   %10.7f  %10.7f  %10.7f\n' % tuple(numpy.zeros(3).tolist()))
    for row in range(3):
    	f.write('   %10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
    fmt = ' %13.5e' * nX + '\n'
    for iz in range(nZ):
    	for iy in range(nY):
    		f.write(fmt % tuple(rho[:,iy,iz].tolist()))		
    f.write('\n')									
    f.write('END_DATAGRID_3D\nEND_BLOCK_DATAGRID_3D')		

##with open(name + '_den_2.xsf', 'w') as f:
#    f.write('Generated by pyscf\n\n')		
#    f.write('CRYSTAL\n')
#    f.write('PRIMVEC\n')	
#    for row in range(3):
#    	f.write('%10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
#    f.write('PRIMVEC\n')
#    for row in range(3):
#    	f.write('%10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
#    f.write('PRIMCOORD\n')
#    f.write('%3d %3d\n' % (num_atoms, 1))
#    for atom in range(len(symbols)):
#    	f.write('%s  %7.7f  %7.7f  %7.7f\n' % (symbols[atom], cart[atom][0], cart[atom][1], cart[atom][2]))				
#    f.write('\n\n')			
#    f.write('BEGIN_BLOCK_DATAGRID_3D\n3D_field\nBEGIN_DATAGRID_3D_UNKNOWN\n')	
#    f.write('   %5d	 %5d  %5d\n' % (nX, nY, nZ))		
#    f.write('   %10.7f  %10.7f  %10.7f\n' % tuple(numpy.zeros(3).tolist()))
#    for row in range(3):
#    	f.write('   %10.7f  %10.7f  %10.7f\n' % (lattice[0, row], lattice[1, row], lattice[2, row]))	
#    fmt = ' %13.5e' * nZ + '\n'
#    for ix in range(nX):
#    	for iy in range(nY):
#    		f.write(fmt % tuple(valores[ix,iy,:].tolist()))		
#    f.write('\n')									
#    f.write('END_DATAGRID_3D\nEND_BLOCK_DATAGRID_3D')		
#
